const bookmarks = [
  {
    title: "Uni",
    links: [
      { name: "lms", url: "https://lms.uwa.edu.au/ultra/stream" },
      { name: "chatgpt", url: "https://chatgpt.com/" },
      { name: "studentConnect", url: "https://student.sims.uwa.edu.au/connect/webconnect" },
      { name: "cyberBook", url: "https://uwacyber.gitbook.io/cits1003" },
      { name: "ctf", url: "https://labs.cits1003.jinhong.org/" },
      { name: "csmarks", url: "https://secure.csse.uwa.edu.au/run/csmarks" },
      { name: "cas", url: "https://apps.cas.uwa.edu.au/even/student?ss=d87664a2b6f64d54b86ba3f57982e3c1" },
      { name: "zlib", url: "https://z-library.se/" },
    ],
  },
  {
    title: "Consoom",
    links: [
      { name: "Youtube", url: "https://youtube.com" },
      { name: "Jellyfin", url: "http://localhost:4206/web/index.html#!/home.html"},
      { name: "Netflix", url: "https://netflix.com" },
      { name: "Amazon Prime", url: "https://primevideo.com" },
      { name: "Reddit", url: "https://old.reddit.com/login" },
    ],
  },
  {
    title: "Hobbies",
    links: [
      { name: "monkeytype", url: "https://monkeytype.com/" },
      { name: "oracle cloud", url: "https://cloud.oracle.com/compute/instances/ocid1.instance.oc1.ap-melbourne-1.anwwkljrptax4xqc52h6b6zocpymm67xg75tyt3kwhwhphlmgord66t4odtq/work-requests?region=ap-melbourne-1" },
      { name: "qmk docs", url: "https://docs.qmk.fm/#/" },
      { name: "r/MK", url: "https://old.reddit.com/r/MechanicalKeyboards" },
      { name: "r/unixporn", url: "https://old.reddit.com/r/unixporn" },
      { name: "github", url: "https://github.com/OddSteak" },
      { name: "gitlab", url: "https://git.disroot.org/OddSteak" },
      { name: "leetCode", url: "https://leetcode.com/" },
      { name: "neetCode", url: "https://neetcode.io/" },
      { name: "codeWars", url: "https://www.codewars.com/" },
      { name: "r/olkb", url: "https://old.reddit.com/r/olkb" },
      { name: "r/startpages", url: "https://old.reddit.com/r/startpages" },
      { name: "via", url: "https://usevia.app/" },
    ],
  },
  {
    title: "Chess",
    links: [
      { name: "lichess", url: "https://lichess.org" },
      { name: "chess.com", url: "https://chess.com/login" },
      { name: "r/chess", url: "https://old.reddit.com/r/chess" },
      { name: "2700chess", url: "https://2700chess.com" },
      { name: "chess-results", url: "https://chess-results.com" },
      { name: "events", url: "https://www.chess.com/events" },
    ],
  },
  {
    title: "Other",
    links: [
      { name: "emacs org-mode", url: "https://orgmode.org/manual/" },
      { name: "emacs guide", url: "https://orgmode.org/guide/" },
      { name: "yt org", url: "https://www.youtube.com/playlist?list=PLVtKhBrRV_ZkPnBtt_TD1Cs9PJlU0IIdE" },
      { name: "emacs wsl", url: "https://shelper.github.io/posts/setup-emacs-in-wsl2/" },
      { name: "magit", url: "https://emacsair.me/2017/09/01/magit-walk-through/" },
      { name: "emacs R", url: "https://www.r-bloggers.com/2022/12/using-emacs-for-r/" },
      { name: "doom emacs", url: "https://github.com/doomemacs/doomemacs/blob/master/docs" },
      { name: "nvim org", url: "https://github.com/nvim-orgmode/orgmode" },
      { name: "Syncthing", url: "http://localhost:8384/" },
      { name: "Radarr", url: "http://localhost:7878/" },
      { name: "Sonarr", url: "http://localhost:8989/" },
      { name: "Bazarr", url: "http://localhost:6767/" },
      { name: "Prowlarr", url: "http://localhost:9696/" },
      { name: "Jellyfin", url: "http://localhost:4206/web/index.html#!/home.html/" },
    ],
  },
];

export default bookmarks
